#!/usr/bin/env python

import sys
import re

if len(sys.argv) < 2:
  print('Need a word ...')
  sys.exit(1)

dictfile = '/usr/share/dict/words'
theword = sys.argv[1]

regex = '.' in theword

with open(dictfile, 'r') as f:
  dict = f.read().split('\n')

if regex:
  for word in dict:
    if re.match(f'^{theword}$', word):
      print(word)
  sys.exit(0)
else:
  keyed_dict = {}
  for word in dict:
    wordkey = ''.join(sorted(list(word)))
    if wordkey in keyed_dict:
      keyed_dict[wordkey].append(word)
    else:
      keyed_dict[wordkey] = [word]
  mykey = ''.join(sorted(list(theword)))
  if mykey in keyed_dict:
    for word in keyed_dict[mykey]:
      print(word)
  else:
    print('No anagram found.')
